# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # Important: Special steps needed for Ubuntu to free port 53: https://github.com/pi-hole/docker-pi-hole?tab=readme-ov-file#installing-on-ubuntu-or-fedora
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: "America/Chicago"
      FTLCONF_webserver_api_password: "{{ vault_pihole.WEBPASSWORD }}"
      FTLCONF_dns_upstreams: "8.8.8.8;8.8.4.4"
      FTLCONF_webserver_port: '80'
      FTLCONF_webserver_tls_cert: ''
      # https://www.reddit.com/r/pihole/comments/1iu44g8/pihole_v6_traefik_fix/
      FTLCONF_webserver_domain: 'pi.hole.{{ vault_domain }}'
      FTLCONF_dns_listeningMode: all
    # Volumes store your data between container upgrades
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped
    pull_policy: always
    dns:
      - 1.1.1.1
    networks:
      - traefik-proxy-network

networks:
  traefik-proxy-network:
    external: true
